SELECT * FROM ohc.comments;
INSERT INTO comments (id, comment, article_id, user_id, created_at, updated_at) VALUE (1, 'Nếu người mẹ có Rh âm (Rh -) kết hợp với người cha cũng có Rh âm thì khi thụ thai, em bé sẽ không có vấn đề gì. Em bé cũng sẽ có nhóm máu có Rh âm nên không có việc sản xuất kháng thể Vấn đề phát sinh khi một người mẹ có nhóm máu Rh âm nhưng mang thai đứa con có nhóm máu Rh dương (Rh +).

Khi người mẹ có Rh âm tiếp xúc với máu của đứa con có Rh dương, người mẹ có khả năng sẽ có phản ứng miễn dịch nên người mẹ mang thai em bé tiếp theo có Rh dương thì các kháng thể anti-D có sẵn này sẽ đi qua nhau thai và tấn công các tế bào hồng cầu của em bé gây ra bệnh tán huyết. Để phòng ngừa cho lần có thai sau, các bà mẹ có Rh âm sẽ được tiêm kháng thể anti-D trong vòng 72 giờ sau khi sinh em bé. Nó sẽ giúp ngăn cản cơ thể người mẹ sản xuất kháng thể kháng Rh dương có khả năng gây ra các vấn đề cho những lần mang thai tiếp theo.

Tuy nhiên, với các bà mẹ có Rh âm thì việc xét nghiệm máu để xác định mức độ kháng thể anti-D sẽ được thực hiện định kỳ trong suốt các thai kỳ tiếp theo. Để tránh nguy hiểm cho em bé, mọi phụ nữ khi mang thai trong lần khám thai đầu cần kiểm tra nhóm máu. Nếu người mẹ có nhóm máu Rh âm, điều này sẽ được ghi vào hồ sơ và sau đó, vào khoảng tuần thứ 28 của thai kỳ, mẹ sẽ được xét nghiệm máu lại để xem đã có kháng thể hay chưa. Cũng cần nói thêm, nếu bà mẹ trước đó có nạo hút thai sảy thai thì cơ thể mẹ cũng có kháng thể kháng RH dương.

Hiện tại, bạn mang thai lần đầu, nếu trước đó chưa nạo hút thì em bé chưa có vấn đề gì cho đến khi sinh. Tuy nhiên, bạn cần đăng ký sinh ở bệnh viện sản để khi sinh bé bị huyết tán (vàng da) sẽ được điều trị ngay và trong 72 giờ sau sinh bạn cần được tiêm kháng thể anti-D để phòng cho lần có thai sau.', 1, 1, NOW(), NOW());
INSERT INTO comments (id, comment, article_id, user_id, created_at, updated_at) VALUE (2, 'Hen phế quản là bệnh rất hay gặp. Hen thường kết hợp với những bệnh nhiễm khuẩn hô hấp Nhiều trường hợp được chẩn đoán là viêm phế quản hay viêm phế quản thể hen thực chất đó là hen phế quản Những trường hợp này sở dĩ có chẩn đoán là hen phế quản vì chữa kháng sinh bệnh nhân cũng đỡ, nhưng hay tái phát.

Vì thế mọi trường hợp được chẩn đoán là viêm phế quản nếu tái phát nhiều lần, chữa đi chữa lại không khỏi phải nghĩ đến hen phế quản hen phế quản có thể do rất nhiều nguyên nhân gây ra nhưng hay gặp là nguyên nhân dị ứng và nhiễm khuẩn. Các chất gây dị ứng (dị nguyên) đường hô hấp có thể gây hen thường gặp là bụi nhà, bụi lông gia súc (chó mèo), đệm thảm len nấm mốc

Nếu nguyên nhân do phấn hoa thì cứ đến mùa hoa đó nở thì người bệnh lại lên cơn hen; Thức ăn cũng có thể là dị nguyên gây dị ứng và phát tác hen như: tôm, cua trứng lạc... Nhiễm khuẩn là một nguyên nhân quan trọng có thể gây hen, trong đó nhiễm khuẩn đường mũi họng hay gây hen và hay gặp nhất vì nó tạo nên một gai kích thích thường xuyên trên đường hô hấp Do đó thường thấy trẻ bị hen khi bị viêm họng viêm mũi viêm amidan…

Ở giai đoạn tiền hen có thể có viêm phế quản cấp tính, viêm phổi… Do đó, triệu chứng của hen rất có thể nhầm với các bệnh hô hấp khác. Lời khuyên, chị nên đưa bé  đến chuyên khoa hô hấp Nhi để khám xác định bệnh, nếu bị hen cần điều trị theo phác đồ kiểm soát hen.', 2, 2, NOW(), NOW());
INSERT INTO comments (id, comment, article_id, user_id, created_at, updated_at) VALUE (3, 'Người bệnh tăng huyết áp cần phải dùng thuốc lâu dài, thậm chí là suốt cả cuộc đời để giữ huyết áp được ổn định, tránh các tai biến do tăng huyết áp gây ra. Tuy nhiên, trong quá trình dùng thuốc này người bệnh cũng không tránh khỏi mắc một số chứng bệnh khác và cần phải dùng thuốc nhưng việc dùng thuốc này lại làm ảnh hưởng đến bệnh và thuốc điều trị tăng huyết áp… Vì vậy, khi đi khám bệnh, người bệnh cần nói rõ tình trạng tăng huyết áp và đang uống thuốc trị huyết áp của mình cho bác sĩ biết để bác sĩ có sự cân nhắc trong kê đơn thuốc.

Ngoài ra, người bệnh tăng huyết áp cần cảnh giác với một số loại thuốc không kê đơn sau:

Thuốc trị ngạt mũi: Bao gồm các thuốc xịt, nhỏ mũi tại chỗ như naphazolin, oxymetazolin hay toàn thân (dùng đường uống) như pseudoephedrine, phenylephrine… Các thuốc này đang được bán rộng rãi trên thị trường và được người bệnh tự ý mua dùng, nhưng đối với người bệnh tim mạch nói chung và tăng huyết áp nói riêng phải rất thận trọng, vì tác động trên tim mạch của các thuốc này bao gồm tăng huyết áp, nhịp tim nhanh và đánh trống ngực… làm trầm trọng thêm bệnh. Đối với phenylephrine, ngoài tác dụng gây tăng huyết áp thì lại gây nhịp tim chậm do phản xạ, làm giảm thể tích máu trong tuần hoàn, giảm lưu lượng máu qua thận, cũng như giảm máu vào nhiều mô và cơ quan của cơ thể. Vì vậy, không dùng cho người bệnh tim mạch nặng nhồi máu cơ tim bệnh mạch vành tăng huyết áp nặng…

Các thuốc giảm đau, chống viêm không steroid: như ibuprofen, naproxen… cũng không được sử dụng đối với bệnh nhân có bệnh tim hoặc tăng huyết áp. Thuốc có thể gây ra những vấn đề về tim, đe dọa tính mạng hoặc các vấn đề lưu thông như cơn đau tim hoặc đột quỵ, đặc biệt là nếu sử dụng thuốc lâu dài. Nguy cơ đau tim hoặc đột quỵ có thể tăng nếu bệnh nhân sử dụng ibuprofen, naproxen với số lượng lớn hơn hoặc lâu hơn so với khuyến cáo.

Để an toàn, người bệnh tim mạch tăng huyết áp khi dùng thuốc điều trị các bệnh thông thường, đặc biệt là các thuốc không kê đơn cần kiểm tra nhãn thuốc, đọc kỹ các thành phần có trong thuốc và các cảnh báo, thận trọng khi dùng trong hướng dẫn sử dụng thuốc để tránh dùng những sản phẩm gây bất lợi cho bệnh của mình.', 3, 3, NOW(), NOW());
INSERT INTO comments (id, comment, article_id, user_id, created_at, updated_at) VALUE (4, 'Trẻ em, đặc biệt là trẻ dưới 1 tuổi thường mắc một số bệnh về da như: chàm, chốc, nấm da... Khi thấy con, em mình xuất hiện các triệu chứng ngoài da, các bà mẹ thường lo lắng nhất là đối với những người nuôi con lần đầu.

Nhiều người nghe mách bảo hoặc đã tự điều trị cho con mình bằng thuốc Nam như dùng các loại lá cây, nhựa cây... tắm hoặc bôi vào vết thương... đã làm cho vết thương không khỏi mà còn sưng hoặc loét ra... hoặc cũng có người tự mua thuốc Tây về chữa như mua flucina, cortibios... bôi cho con. Kết quả của những thói quen như vậy đã dẫn tới nhiều cháu bệnh không khỏi mà trở nên nặng hơn. Do dùng thuốc không đúng nên bệnh từ nhẹ trở thành trầm trọng phải đưa đi cấp cứu ở các bệnh viện tuyến trên.Để chữa bệnh có hiệu quả và tránh những tai biến do thuốc gây ra, khi các bà mẹ phát hiện thấy con mình có biểu hiện mắc bệnh về da tốt nhất nên đưa các cháu tới khám và điều trị tại các cơ sở chuyên khoa da liễu. Đối với từng loại bệnh, từng giai đoạn phát triển của bệnh sẽ có phương pháp điều trị, dùng thuốc khác nhau. Nếu đúng là bệnh chàm việc dùng thuốc cần phù hợp với từng giai đoạn bệnh.

Ví dụ bệnh chàm ở giai đoạn sớm khi da mới đỏ và chảy nước dùng hồ nước bôi lên thương tổn, ở giai đoạn cấp có thể dùng dung dịch yarish, nước muối thuốc tím Khi thương tổn đã khô có thể dùng dạng thuốc mỡ. Các thuốc corticoid được dùng chữa chàm cho kết quả tốt nhưng phải dùng đúng chỉ định, đúng phương pháp, đúng các dạng thuốc và nồng độ thích hợp...  để tránh tai biến do thuốc, đặc biệt đối với trẻ nhỏ.

Thuốc chữa bệnh là con dao hai lưỡi, sử dụng đúng thuốc có tác dụng tốt, sử dụng sai thuốc ', 4, 4, NOW(), NOW());
INSERT INTO comments (id, comment, article_id, user_id, created_at, updated_at) VALUE (5, 'Có hơn 200 dạng viêm khớp khác nhau nhưng hai dạng viêm khớp gặp phổ biến nhất là thoái hóa khớp và viêm khớp dạng thấp viêm khớp dạng thấp là bệnh tự miễn một số người gọi viêm đa khớp không xác định vì đây là bệnh viêm không đặc hiệu. Hiểu đơn giản là hệ thống miễn dịch của cơ thể tấn công chính các tế bào khỏe mạnh của cơ thể, như mô, khớp, các cơ quan và xử lý chúng giống như một tác nhân xâm nhập từ bên ngoài vậy.

Tuy nhiên, mẹ bạn năm nay 49 tuổi (gọi tuổi tiền mãn kinh), do đó có thể gặp một số rối loạn tiền mãn kinh do sự suy giảm nội tiết ở tuổi này. Đau khớp rối loạn nhịp tim là một trong những biểu hiện thường gặp ở phụ nữ tuổi tiền mãn kinh Còn viêm và xuất huyết bao tử thì do nhiều nguyên nhân, trong đó có nguyên nhân do dùng thuốc giảm đau như aspirin hoặc dùng thuốc có chứa corticoide trong điều trị viêm đa khớp...

Còn rối loạn nhịp tim của mẹ bạn cần xác định xem đây là tổn thương thực thể tại tim hay do rối loạn thần kinh thực vật. Nếu có tổn thương tại tim thì phải điều trị tích cực để tránh các biến chứng nguy hiểm như đột quỵ do tim. Trường hợp do rối loạn thần kinh thực vật gây loạn nhịp thì không đáng ngại. Điều quan trọng là việc dùng thuốc theo chỉ định của bác sĩ. Ngoài ra, cần chú ý về chế độ dinh dưỡng đủ chất để cơ thể không bị thiếu chất, vì khi thiếu magie-B6, triệu chứng tiền mãn kinh nguyệt càng thêm trầm trọng; hay như thiếu canxi sẽ gây loãng xương thì dễ bị đau nhức xương khớp.', 5, 5, NOW(), NOW());
INSERT INTO comments (id, comment, article_id, user_id, created_at, updated_at) VALUE (6, 'Táo bón là tình trạng trẻ đi ngoài phân rắn khô khi đi phải rặn nhiều hoặc khoảng cách giữa 2 lần đại tiện quá xa nhau Trẻ 0 - 2 tuổi mà trên 2 ngày mới đi ngoài 1 lầntrẻ từ 2 tuổi trở lên kể cả người lớn mà trên 3 ngày mới đi ngoài 1 lần thì dù phân mềmlỏng vẫn được coi là táo bón

Trẻ 1 - 3 tháng tuổi nguyên nhân táo bón thường do chế độ ăn: mẹ bị táo bón ăn sữa công thức nhiều chất đạm không bổ sung chất xơ hòa tan và vi khuẩn có lợi pha sữa không đúng tỷ lệ dẫn đến thiếu nước thừa canxi do mẹ uống thuốc bổ sung canxi sau sinh, nằm trong phòng điều hòa liên tục… Ngoài ra trẻ mắc bệnh còi xương thiếu máu cũng bị táo bón
Nếu cháu bú mẹ hoàn toàn thì quan trọng nhất là chế độ ăn của mẹ: phải ăn nhiều rau quả, uống nhiều nước..., ngoài ra có thể uống thêm chất xơ hòa tan

Với bé, bạn nên xoa bụng cho trẻ theo chiều kim đồng hồ từ phải qua trái xoa quanh rốn (khung đại tràng) ngày 3 - 4 lần, mỗi lần 10 phút vào khoảng cách giữa 2 bữa ăn để kích thích nhu động ruột.

Cho trẻ uống bổ sung nước, theo dõi lượng và màu của nước tiểu của trẻ. Nếu nước tiểu trong, nhiều chứng tỏ bé đã được cung cấp đủ nước và nếu nước tiểu ít và có màu vàng là do bé bị thiếu nước.

Ngoài ra, chị cũng nên cho bé đi khám bác sĩ xem có bị còi xương thiếu máu hay dị tật về đường tiêu hóa không nếu tình trạng táo bón kéo dài.', 6, 6, NOW(), NOW());

INSERT INTO comments (id, comment, article_id, user_id, created_at, updated_at) VALUE (7, 'Bệnh viêm gan siêu vi B có 2 dạng thường gặp: người lành mang bệnh viêm gan cấp hoặc mạn. Thống kê cho thấy người lành mang mầm bệnh siêu vi B chiếm khoảng 10-15% dân số.

Những trường hợp khi xét nghiệm máu có HbsAg(+) và men gan vẫn bình thường, toàn trạng không có biểu hiện gì bất thường (không có triệu chứng gì) gọi người lành mang mầm bệnh. Những người lành mang mầm bệnh vẫn có thể chung sống hòa bình với siêu vi B đến suốt đời.

Trường hợp thứ 2 là viêm gan cấp hoặc mạn do vi-rút viêm gan b viêm gan cấp thường tự khỏi sau vài tuần, một số trở thành viêm gan mạn viêm gan mạn thường có rất ít triệu chứng như đau hạ sườn phải ăn không ngon, xét nghiệm men gan tăng. Nếu bị viêm gan mạn thì bắt buộc phải điều trị vì dễ dẫn đến biến chứng xơ gan ung thư gan sau này.

Như thư bạn nói thì bạn là người lành mang mầm bệnh nên chưa cần điều trị mà nên có một chế độ ăn uống, sinh hoạt lành mạnh như: chế độ ăn hợp lý, nhiều rau xanh và quả tươi, ít mỡ động vật, không uống rượu, không hút thuốc lá... và định kỳ khám để theo dõi sức khỏe của gan (siêu âm ổ bụng, xét nghiệm máu )', 7, 7, NOW(), NOW());
INSERT INTO comments (id, comment, article_id, user_id, created_at, updated_at) VALUE (8, 'Những vùng da mỏng yếu rất dễ bị giãn ra tạo thành các vết rạn khi cơ thể có sự thay đổi nhất là khi tăng cân Đó chính là lý do tại sao nhiều phụ nữ mang thai người béo phì thanh niên tuổi mới lớn da thường có vết rạn ở vùng bụng, ngực và đùi.

Ngoài ra nguyên nhân gây rạn da có thể là do hormon Những thay đổi về hormon trong thời kỳ dậy thì (và cả trong thời kỳ thai nghén) đã làm hạn chế tính đàn hồi của da và gây nên rạn da mạnh. Rạn da cũng có yếu tố di truyền, nếu người mẹ bị thì con gái cũng hay bị.Biểu hiện lúc đầu là những vệt đỏ, đỏ tím, có hoặc không kèm theo ngứa hoặc dấm dứt nhẹ tại chỗ. Sau đó, da chuyển sang màu trắng có ánh như xà cừ và hình thành các đường rạch lõm (là lúc tạo vết rạn), sự tương phản khá rõ giữa làn da bình thường và vết rạn.

Rạn da không phải là bệnh, nên cháu không nên lo lắng mà ảnh hưởng đến sức khỏe và việc học tập Nếu da rạn nhiều, có thể bôi các loại kem chống rạn da theo chỉ định của bác sĩ. Tuyệt đối không dùng kem bôi có corticoid có nhiều tác dụng phụ nguy hiểm, làm cho rạn da nhiều hơn.', 8, 8, NOW(), NOW());
INSERT INTO comments (id, comment, article_id, user_id, created_at, updated_at) VALUE (9, 'Có nhiều nguyên nhân rối loạn tiền đình trong đó có thể là do động mạch mang máu đến nuôi não bộ bị thiểu năngKhi bị bệnh có thể dùng các thuốc cải thiện tuần hoàn não sẽ đỡ. Tuy nhiên, để điều trị dứt bệnh cần khám xác định nguyên nhân, từ đó bác sĩ sẽ tư vấn phương pháp điều trị rối loạn tiền đình phù hợp.Điều trị rối loạn tiền đình ngày nay chủ yếu là điều trị nội khoa về chế độ thuốc men và thời gian hoàn toàn phải do bác sĩ chỉ định Bạn có thể đi khám ở bệnh viện đa khoa nếu cần bác sĩ sẽ chỉ định làm một số xét nghiệm liên quan như: đo điện não đồ chụp mạch não... giúp chẩn đoán chính xác nguyên nhân.

Cần lưu ý là những người làm việc văn phòngngồi nhiều trong phòng máy lạnh và ngồi nhiều trước máy vi tính dễ bị rối loạn tiền đình... Do vậy, trước hết bạn cần bố trí thời gian học tập nghỉ ngơi hợp lý, không thức quá khuya, dành thời gian để tập thể dục đều đặn; đi ngủ đúng giờ để có giấc ngủ sâu sẽ không bị bóng đè.

Thực chất của bóng đè là do ngủ không sâu giấc Chú ý dinh dưỡng đầy đủ, giải tỏa stress Nếu tình trạng bệnh không cải thiện bạn nên đi khám chuyên khoa nội thần kinh để được kê đơn điều trị đúng.', 9, 9, NOW(), NOW());
INSERT INTO comments (id, comment, article_id, user_id, created_at, updated_at) VALUE (10, 'Huyết áp được coi là bình thường khi số đo huyết áp tâm thu dưới 120mmHg và huyết áp tâm trương dưới 80mmHg. Huyết áp kẹt khi huyết áp tâm thu - huyết áp tâm trương nhỏ hơn hoặc bằng  20 - 25mmHg.Huyết áp kẹt thường gặp ở người có cơ địa huyết áp thấp nhưng huyết áp cao cũng có thể gặp Ví dụ: Huyết áp tâm thu bằng 110 thì huyết áp tâm trương vào khoảng 65 - 75 là bình thường Nếu huyết áp tâm trương là 85 - 90 thì có thể coi là huyết áp kẹt Người bệnh thường thấy đau đầu ngủ kém mệt mỏi khó thở thỉnh thoảng thấy hoa Mắt chóng mặt hơi thở ngắn nói hụt hơi...

Nguyên nhân gây kẹt huyết áp có thể do suy tim bệnh van tim (hẹp van động mạch chủhẹp van 2 lá)... Ngoài ra còn có các nguyên nhân khác: Chèn ép tim (tràn máu tràn dịch màng ngoài tim). Cổ trướng cũng gây huyết áp kẹt... Huyết áp kẹt nguy hiểm là làm ứ trệ tuần hoàn, dễ gây phì đại thất trái dẫn đến suy tim

Các bệnh liên quan đến huyết áp (huyết áp thấp, tăng huyết áp, huyết áp kẹt) đều không tốt cho sức khoẻ, cần tới cơ sở y tế để được khám và tư vấn điều trị thích hợp.

Trường hợp của anh cần đi khám lại tại cơ sở y tế chuyên khoa, không chỉ đo huyết áp mà còn làm thêm một số thăm dò tim để tìm nguyên nhân và can thiệp kịp thời, tránh chủ quan sẽ nguy hiểm tính mạng.', 10, 10, NOW(), NOW());
INSERT INTO comments (id, comment, article_id, user_id, created_at, updated_at) VALUE (11, 'Theo thông tin của bạn về tình trạng của cháu ở trên, có thể nghĩ đến cháu bị tràn dịch màng tinh hoàn Trong thời kỳ bào thai, đến tuần thứ 28 tinh hoàn mới di chuyển từ ổ bụng xuống bìu thông qua ống phúc tinh mạc.Phần lớn chất dịch sẽ tự thoát ra ngoài trước khi các ống phúc tinh mạc này đóng lại Trường hợp dịch vẫn còn sau khi ống phúc tinh mạc đóng lại và dịch không thể thoát về ổ bụng thì  khoảng sau 1 năm chúng cũng tự biến mất Ở người lớn tuổi tràn dịch màng tinh hoàn có thể là do viêm mào tinh hoàn hoặc viêm tinh hoàn

Tràn dịch màng tinh hoàn cần phải điều trị bằng phẫu thuật lộn màng tinh hoàn Sau phẫu thuật, tinh hoàn vẫn bình thường, không ảnh hưởng đến chức năng sinh sản sau này. Thời gian để mổ tốt nhất là khi cháu được 6 - 8 tuổi, để có thể chỉ phải gây tê tại chỗ, tránh gây mê, ảnh hưởng đến thần kinh của trẻ. Tuy nhiên, trong trường hợp cháu bị tràn dịch gây sưng to tinh hoàn, ảnh hưởng đến sinh hoạt thì cần phải mổ sớm hơn. Bạn nên đưa con đến chuyên khoa tiết niệu sinh dục của bệnh viện để được chẩn đoán và điều trị đúng.', 11, 11, NOW(), NOW());