SELECT * FROM ohc.comments;
INSERT INTO comments (id, comment, article_id, user_id, created_at, updated_at) VALUE (1, 'Nếu người mẹ có Rh âm (Rh -) kết hợp với người cha cũng có Rh âm thì khi thụ thai, em bé sẽ không có vấn đề gì. Em bé cũng sẽ có nhóm máu có Rh âm nên không có việc sản xuất kháng thể Vấn đề phát sinh khi một người mẹ có nhóm máu Rh âm nhưng mang thai đứa con có nhóm máu Rh dương (Rh +).

Khi người mẹ có Rh âm tiếp xúc với máu của đứa con có Rh dương, người mẹ có khả năng sẽ có phản ứng miễn dịch nên người mẹ mang thai em bé tiếp theo có Rh dương thì các kháng thể anti-D có sẵn này sẽ đi qua nhau thai và tấn công các tế bào hồng cầu của em bé gây ra bệnh tán huyết. Để phòng ngừa cho lần có thai sau, các bà mẹ có Rh âm sẽ được tiêm kháng thể anti-D trong vòng 72 giờ sau khi sinh em bé. Nó sẽ giúp ngăn cản cơ thể người mẹ sản xuất kháng thể kháng Rh dương có khả năng gây ra các vấn đề cho những lần mang thai tiếp theo.

Tuy nhiên, với các bà mẹ có Rh âm thì việc xét nghiệm máu để xác định mức độ kháng thể anti-D sẽ được thực hiện định kỳ trong suốt các thai kỳ tiếp theo. Để tránh nguy hiểm cho em bé, mọi phụ nữ khi mang thai trong lần khám thai đầu cần kiểm tra nhóm máu. Nếu người mẹ có nhóm máu Rh âm, điều này sẽ được ghi vào hồ sơ và sau đó, vào khoảng tuần thứ 28 của thai kỳ, mẹ sẽ được xét nghiệm máu lại để xem đã có kháng thể hay chưa. Cũng cần nói thêm, nếu bà mẹ trước đó có nạo hút thai sảy thai thì cơ thể mẹ cũng có kháng thể kháng RH dương.

Hiện tại, bạn mang thai lần đầu, nếu trước đó chưa nạo hút thì em bé chưa có vấn đề gì cho đến khi sinh. Tuy nhiên, bạn cần đăng ký sinh ở bệnh viện sản để khi sinh bé bị huyết tán (vàng da) sẽ được điều trị ngay và trong 72 giờ sau sinh bạn cần được tiêm kháng thể anti-D để phòng cho lần có thai sau.', 1, 1, NOW(), NOW());
INSERT INTO comments (id, comment, article_id, user_id, created_at, updated_at) VALUE (2, 'Hen phế quản là bệnh rất hay gặp. Hen thường kết hợp với những bệnh nhiễm khuẩn hô hấp Nhiều trường hợp được chẩn đoán là viêm phế quản hay viêm phế quản thể hen thực chất đó là hen phế quản Những trường hợp này sở dĩ có chẩn đoán là hen phế quản vì chữa kháng sinh bệnh nhân cũng đỡ, nhưng hay tái phát.

Vì thế mọi trường hợp được chẩn đoán là viêm phế quản nếu tái phát nhiều lần, chữa đi chữa lại không khỏi phải nghĩ đến hen phế quản hen phế quản có thể do rất nhiều nguyên nhân gây ra nhưng hay gặp là nguyên nhân dị ứng và nhiễm khuẩn. Các chất gây dị ứng (dị nguyên) đường hô hấp có thể gây hen thường gặp là bụi nhà, bụi lông gia súc (chó mèo), đệm thảm len nấm mốc

Nếu nguyên nhân do phấn hoa thì cứ đến mùa hoa đó nở thì người bệnh lại lên cơn hen; Thức ăn cũng có thể là dị nguyên gây dị ứng và phát tác hen như: tôm, cua trứng lạc... Nhiễm khuẩn là một nguyên nhân quan trọng có thể gây hen, trong đó nhiễm khuẩn đường mũi họng hay gây hen và hay gặp nhất vì nó tạo nên một gai kích thích thường xuyên trên đường hô hấp Do đó thường thấy trẻ bị hen khi bị viêm họng viêm mũi viêm amidan…

Ở giai đoạn tiền hen có thể có viêm phế quản cấp tính, viêm phổi… Do đó, triệu chứng của hen rất có thể nhầm với các bệnh hô hấp khác. Lời khuyên, chị nên đưa bé  đến chuyên khoa hô hấp Nhi để khám xác định bệnh, nếu bị hen cần điều trị theo phác đồ kiểm soát hen.', 2, 2, NOW(), NOW());
INSERT INTO comments (id, comment, article_id, user_id, created_at, updated_at) VALUE (3, 'Người bệnh tăng huyết áp cần phải dùng thuốc lâu dài, thậm chí là suốt cả cuộc đời để giữ huyết áp được ổn định, tránh các tai biến do tăng huyết áp gây ra. Tuy nhiên, trong quá trình dùng thuốc này người bệnh cũng không tránh khỏi mắc một số chứng bệnh khác và cần phải dùng thuốc nhưng việc dùng thuốc này lại làm ảnh hưởng đến bệnh và thuốc điều trị tăng huyết áp… Vì vậy, khi đi khám bệnh, người bệnh cần nói rõ tình trạng tăng huyết áp và đang uống thuốc trị huyết áp của mình cho bác sĩ biết để bác sĩ có sự cân nhắc trong kê đơn thuốc.

Ngoài ra, người bệnh tăng huyết áp cần cảnh giác với một số loại thuốc không kê đơn sau:

Thuốc trị ngạt mũi: Bao gồm các thuốc xịt, nhỏ mũi tại chỗ như naphazolin, oxymetazolin hay toàn thân (dùng đường uống) như pseudoephedrine, phenylephrine… Các thuốc này đang được bán rộng rãi trên thị trường và được người bệnh tự ý mua dùng, nhưng đối với người bệnh tim mạch nói chung và tăng huyết áp nói riêng phải rất thận trọng, vì tác động trên tim mạch của các thuốc này bao gồm tăng huyết áp, nhịp tim nhanh và đánh trống ngực… làm trầm trọng thêm bệnh. Đối với phenylephrine, ngoài tác dụng gây tăng huyết áp thì lại gây nhịp tim chậm do phản xạ, làm giảm thể tích máu trong tuần hoàn, giảm lưu lượng máu qua thận, cũng như giảm máu vào nhiều mô và cơ quan của cơ thể. Vì vậy, không dùng cho người bệnh tim mạch nặng nhồi máu cơ tim bệnh mạch vành tăng huyết áp nặng…

Các thuốc giảm đau, chống viêm không steroid: như ibuprofen, naproxen… cũng không được sử dụng đối với bệnh nhân có bệnh tim hoặc tăng huyết áp. Thuốc có thể gây ra những vấn đề về tim, đe dọa tính mạng hoặc các vấn đề lưu thông như cơn đau tim hoặc đột quỵ, đặc biệt là nếu sử dụng thuốc lâu dài. Nguy cơ đau tim hoặc đột quỵ có thể tăng nếu bệnh nhân sử dụng ibuprofen, naproxen với số lượng lớn hơn hoặc lâu hơn so với khuyến cáo.

Để an toàn, người bệnh tim mạch tăng huyết áp khi dùng thuốc điều trị các bệnh thông thường, đặc biệt là các thuốc không kê đơn cần kiểm tra nhãn thuốc, đọc kỹ các thành phần có trong thuốc và các cảnh báo, thận trọng khi dùng trong hướng dẫn sử dụng thuốc để tránh dùng những sản phẩm gây bất lợi cho bệnh của mình.', 3, 3, NOW(), NOW());
INSERT INTO comments (id, comment, article_id, user_id, created_at, updated_at) VALUE (4, 'Trẻ em, đặc biệt là trẻ dưới 1 tuổi thường mắc một số bệnh về da như: chàm, chốc, nấm da... Khi thấy con, em mình xuất hiện các triệu chứng ngoài da, các bà mẹ thường lo lắng nhất là đối với những người nuôi con lần đầu.

Nhiều người nghe mách bảo hoặc đã tự điều trị cho con mình bằng thuốc Nam như dùng các loại lá cây, nhựa cây... tắm hoặc bôi vào vết thương... đã làm cho vết thương không khỏi mà còn sưng hoặc loét ra... hoặc cũng có người tự mua thuốc Tây về chữa như mua flucina, cortibios... bôi cho con. Kết quả của những thói quen như vậy đã dẫn tới nhiều cháu bệnh không khỏi mà trở nên nặng hơn. Do dùng thuốc không đúng nên bệnh từ nhẹ trở thành trầm trọng phải đưa đi cấp cứu ở các bệnh viện tuyến trên.Để chữa bệnh có hiệu quả và tránh những tai biến do thuốc gây ra, khi các bà mẹ phát hiện thấy con mình có biểu hiện mắc bệnh về da tốt nhất nên đưa các cháu tới khám và điều trị tại các cơ sở chuyên khoa da liễu. Đối với từng loại bệnh, từng giai đoạn phát triển của bệnh sẽ có phương pháp điều trị, dùng thuốc khác nhau. Nếu đúng là bệnh chàm việc dùng thuốc cần phù hợp với từng giai đoạn bệnh.

Ví dụ bệnh chàm ở giai đoạn sớm khi da mới đỏ và chảy nước dùng hồ nước bôi lên thương tổn, ở giai đoạn cấp có thể dùng dung dịch yarish, nước muối thuốc tím Khi thương tổn đã khô có thể dùng dạng thuốc mỡ. Các thuốc corticoid được dùng chữa chàm cho kết quả tốt nhưng phải dùng đúng chỉ định, đúng phương pháp, đúng các dạng thuốc và nồng độ thích hợp...  để tránh tai biến do thuốc, đặc biệt đối với trẻ nhỏ.

Thuốc chữa bệnh là con dao hai lưỡi, sử dụng đúng thuốc có tác dụng tốt, sử dụng sai thuốc ', 4, 4, NOW(), NOW());
INSERT INTO comments (id, comment, article_id, user_id, created_at, updated_at) VALUE (5, 'Có hơn 200 dạng viêm khớp khác nhau nhưng hai dạng viêm khớp gặp phổ biến nhất là thoái hóa khớp và viêm khớp dạng thấp viêm khớp dạng thấp là bệnh tự miễn một số người gọi viêm đa khớp không xác định vì đây là bệnh viêm không đặc hiệu. Hiểu đơn giản là hệ thống miễn dịch của cơ thể tấn công chính các tế bào khỏe mạnh của cơ thể, như mô, khớp, các cơ quan và xử lý chúng giống như một tác nhân xâm nhập từ bên ngoài vậy.

Tuy nhiên, mẹ bạn năm nay 49 tuổi (gọi tuổi tiền mãn kinh), do đó có thể gặp một số rối loạn tiền mãn kinh do sự suy giảm nội tiết ở tuổi này. Đau khớp rối loạn nhịp tim là một trong những biểu hiện thường gặp ở phụ nữ tuổi tiền mãn kinh Còn viêm và xuất huyết bao tử thì do nhiều nguyên nhân, trong đó có nguyên nhân do dùng thuốc giảm đau như aspirin hoặc dùng thuốc có chứa corticoide trong điều trị viêm đa khớp...

Còn rối loạn nhịp tim của mẹ bạn cần xác định xem đây là tổn thương thực thể tại tim hay do rối loạn thần kinh thực vật. Nếu có tổn thương tại tim thì phải điều trị tích cực để tránh các biến chứng nguy hiểm như đột quỵ do tim. Trường hợp do rối loạn thần kinh thực vật gây loạn nhịp thì không đáng ngại. Điều quan trọng là việc dùng thuốc theo chỉ định của bác sĩ. Ngoài ra, cần chú ý về chế độ dinh dưỡng đủ chất để cơ thể không bị thiếu chất, vì khi thiếu magie-B6, triệu chứng tiền mãn kinh nguyệt càng thêm trầm trọng; hay như thiếu canxi sẽ gây loãng xương thì dễ bị đau nhức xương khớpcomments', 5, 5, NOW(), NOW());